#!/usr/bin/env python3.14 
"""
    Sucht nach javascriptdateien im angegeben input-Verzeichnis
    und scannt sie und fügt "export" vor den angegeben Strings
    um danach `typedoc` benutzen zu können, welches nur exports
    dokumentiert.
"""


from argparse import ArgumentParser
from pathlib import Path
from glob import glob
from shutil import rmtree

file_dir_in="src/components/"
file_dir_out="src4doc/"
filepath_in=""
filepath_out=""

parser = ArgumentParser()
parser.add_argument("-i","--inputdir",
                    default="src",
                    dest="sourcedir",
                    )
parser.add_argument("--clean",
                    dest="clean",
                    action="store_true")


def js_all_export(argv:list[str]|None=None):
    args = parser.parse_args(argv)
    print(f"scan inputdir: {args.sourcedir}")

    if args.clean:
        rmtree(file_dir_out)
        return
    
    file_dir_in = args.sourcedir
    for file_ in glob(file_dir_in+"/*.js"):
        print(f"scan file: {file_}")
        filepath_in=Path(file_)
        filepath_out = list(filepath_in.parts)
        filepath_out[0]=file_dir_out
        filepath_out = Path("/".join(filepath_out))
        if not filepath_out.parent.exists():
            filepath_out.parent.mkdir(parents=True, exist_ok=True)


        with (filepath_in.open() as fi,     
            filepath_out.open("w") as fo):
            for line in fi:
                newline = ""
                if line.strip().startswith("const log"):
                    continue
                elif line.strip().startswith("log("):
                    continue
                elif line.startswith("function"):
                    newline = line.replace("function","export function",1)
                    print(line)
                    print(newline)
                elif line.startswith("class"):
                    newline = line.replace("class","export class",1)
                    print(line)
                    print(newline)
                elif line.startswith("const"):
                    newline = line.replace("const","export const", 1)
                    print(line)
                    print(newline)
                elif line.startswith("let"):
                    newline = line.replace("let","export let", 1)
                    print(line)
                    print(newline)
                elif line.startswith("var"):
                    newline = line.replace("var","export var", 1)
                    print(line)
                    print(newline)
                if not newline:
                    newline = line
                fo.write(newline)

js_all_export()        

